# Generated by Django 4.2.5 on 2023-09-28 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HeaderData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('location', models.CharField(max_length=250)),
                ('social_media_account', models.CharField(choices=[('FB', 'Facebook'), ('TW', 'Twitter'), ('IN', 'LinkedIn'), ('IG', 'Instagram')], max_length=50)),
            ],
        ),
    ]
