# Generated by Django 4.2.5 on 2023-09-28 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='headerdata',
            name='social_media_account',
        ),
        migrations.CreateModel(
            name='SocialMediaLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('FB', 'Facebook'), ('TW', 'Twitter'), ('IN', 'LinkedIn'), ('IG', 'Instagram')], max_length=50)),
                ('link', models.URLField()),
                ('header_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_media_links', to='home.headerdata')),
            ],
        ),
    ]
