# Generated by Django 4.2.5 on 2023-09-29 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_headerdata_logo_alter_socialmedialink_platform'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='Slider Images/%Y-%m-%d')),
                ('location', models.CharField(max_length=100)),
                ('text', models.TextField(max_length=500)),
            ],
        ),
    ]
