# Generated by Django 4.2.5 on 2023-10-01 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_rename_location_slider_city_slider_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('background_image', models.ImageField(upload_to='Video Section/Background Images/%Y-%m-%d')),
                ('text', models.CharField(max_length=150)),
                ('video_thumbnail', models.ImageField(upload_to='Video Section/Thumbnail Images/%Y-%m-%d')),
                ('link', models.URLField()),
            ],
        ),
    ]
