# Generated by Django 4.2.6 on 2023-10-11 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='FunFacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buildings_finished', models.PositiveIntegerField()),
                ('years_experience', models.PositiveIntegerField()),
                ('awards_won_date', models.PositiveBigIntegerField(help_text='Enter awards won year:')),
                ('awards_won', models.PositiveIntegerField()),
            ],
        ),
    ]
