# Generated by Django 4.2.6 on 2023-10-12 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_funfacts'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=250)),
                ('message', models.TextField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='funfacts',
            options={'verbose_name': 'Fun Facts', 'verbose_name_plural': 'Fun Facts'},
        ),
        migrations.AddField(
            model_name='headerdata',
            name='map_link',
            field=models.URLField(default='a.com', help_text='Enter google map embed link'),
            preserve_default=False,
        ),
    ]
