# Generated by Django 4.2.6 on 2023-10-12 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_message_alter_funfacts_options_headerdata_map_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='headerdata',
            name='map_link',
            field=models.TextField(help_text='Enter google map embed link'),
        ),
    ]
