# Generated by Django 4.2.6 on 2023-10-13 15:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_contact_remove_headerdata_map_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='headerdata',
            name='number',
            field=models.CharField(default='l', max_length=50, validators=[django.core.validators.RegexValidator('[+0123456789]', 'Wrong phone number!')]),
            preserve_default=False,
        ),
    ]
