# Generated by Django 4.2.6 on 2023-10-13 16:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_headerdata_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='headerdata',
            name='number',
            field=models.CharField(help_text='Enter your phone number', max_length=50, validators=[django.core.validators.RegexValidator('[+0123456789]+$', 'Wrong phone number!')], verbose_name='Phone Number'),
        ),
    ]
