# Generated by Django 4.2.6 on 2023-10-13 16:35

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_footer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footer',
            name='footer_text',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
