# Generated by Django 4.2.6 on 2023-10-14 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_alter_footer_footer_text'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='footer',
            options={'verbose_name_plural': 'Footer Section'},
        ),
    ]
